// ── Utility Functions ──────────────────────────────────────────────────

export function ts(): string {
  return new Date().toLocaleTimeString();
}

export function escapeHtml(str: string): string {
  const d = document.createElement('div');
  d.textContent = str;
  return d.innerHTML;
}

export function debounce<T extends (...args: unknown[]) => void>(
  fn: T,
  delay: number
): (...args: Parameters<T>) => void {
  let timeout: ReturnType<typeof setTimeout> | null = null;
  return (...args: Parameters<T>) => {
    if (timeout) clearTimeout(timeout);
    timeout = setTimeout(() => fn(...args), delay);
  };
}

export function showResult(el: HTMLElement, ok: boolean, text: string): void {
  el.textContent = text;
  el.className = `action-result visible ${ok ? 'ok' : 'err'}`;
}

// ── WoW Constants ───────────────────────────────────────────────────────

export const MAP_NAMES: Record<number, string> = {
  0: 'Eastern Kingdoms',
  1: 'Kalimdor',
  13: 'Test',
  25: 'Scott Test',
  29: 'CashTest',
  30: 'Alterac Valley',
  33: 'Shadowfang Keep',
  34: 'Stormwind Stockade',
  36: 'Deadmines',
  43: 'Wailing Caverns',
  44: 'Monastery',
  47: 'Razorfen Kraul',
  48: 'Blackfathom Deeps',
  70: 'Uldaman',
  90: 'Gnomeregan',
  109: 'Sunken Temple',
  129: 'Razorfen Downs',
  189: 'Scarlet Monastery',
  209: "Zul'Farrak",
  229: 'Blackrock Spire',
  230: 'Blackrock Depths',
  249: "Onyxia's Lair",
  269: 'Opening of the Dark Portal',
  289: 'Scholomance',
  309: "Zul'Gurub",
  329: 'Stratholme',
  349: 'Maraudon',
  369: 'Deeprun Tram',
  389: 'Ragefire Chasm',
  409: 'Molten Core',
  429: 'Dire Maul',
  469: 'Blackwing Lair',
  489: 'Warsong Gulch',
  509: "Ruins of Ahn'Qiraj",
  529: 'Arathi Basin',
  530: 'Outland',
  531: "Ahn'Qiraj Temple",
  532: 'Karazhan',
  533: 'Naxxramas',
  534: 'Battle for Mount Hyjal',
  540: 'Shattered Halls',
  542: 'Blood Furnace',
  543: 'Hellfire Ramparts',
  544: "Magtheridon's Lair",
  545: 'The Steamvault',
  546: 'The Underbog',
  547: 'The Slave Pens',
  548: 'Serpentshrine Cavern',
  550: 'Tempest Keep',
  552: 'The Arcatraz',
  553: 'The Botanica',
  554: 'The Mechanar',
  555: 'Shadow Labyrinth',
  556: 'Sethekk Halls',
  557: 'Mana-Tombs',
  558: 'Auchenai Crypts',
  559: 'Nagrand Arena',
  560: 'Escape From Durnholde',
  562: "Blade's Edge Arena",
  564: 'Black Temple',
  565: "Gruul's Lair",
  566: 'Eye of the Storm',
  568: "Zul'Aman",
  571: 'Northrend',
  572: 'Ruins of Lordaeron',
  574: 'Utgarde Keep',
  575: 'Utgarde Pinnacle',
  576: 'The Nexus',
  578: 'The Oculus',
  580: 'Sunwell Plateau',
  585: "Magisters' Terrace",
  595: 'Culling of Stratholme',
  599: 'Halls of Stone',
  600: "Drak'Tharon Keep",
  601: 'Azjol-Nerub',
  602: 'Halls of Lightning',
  603: 'Ulduar',
  604: 'Gundrak',
  607: 'Strand of the Ancients',
  608: 'Violet Hold',
  609: 'Acherus: The Ebon Hold',
  615: 'Obsidian Sanctum',
  616: 'Eye of Eternity',
  617: 'Dalaran Sewers',
  618: 'Ring of Valor',
  619: "Ahn'kahet: The Old Kingdom",
  624: 'Vault of Archavon',
  631: 'Icecrown Citadel',
  632: 'Forge of Souls',
  649: 'Trial of the Crusader',
  650: 'Trial of the Champion',
  658: 'Pit of Saron',
  668: 'Halls of Reflection',
  724: 'The Ruby Sanctum',
};

export const ZONE_NAMES: Record<number, string> = {
  1: 'Dun Morogh',
  3: 'Badlands',
  4: 'Blasted Lands',
  8: 'Swamp of Sorrows',
  10: 'Duskwood',
  11: 'Wetlands',
  12: 'Elwynn Forest',
  14: 'Durotar',
  15: 'Dustwallow Marsh',
  16: 'Azshara',
  17: 'The Barrens',
  25: 'Blackrock Mountain',
  28: 'Western Plaguelands',
  33: 'Stranglethorn Vale',
  36: 'Alterac Mountains',
  38: 'Loch Modan',
  40: 'Westfall',
  44: 'Redridge Mountains',
  45: 'Arathi Highlands',
  46: 'Burning Steppes',
  47: 'The Hinterlands',
  51: 'Searing Gorge',
  65: 'Dragonblight',
  66: "Zul'Drak",
  67: 'The Storm Peaks',
  85: 'Tirisfal Glades',
  130: 'Silverpine Forest',
  139: 'Eastern Plaguelands',
  141: 'Teldrassil',
  148: 'Darkshore',
  210: 'Icecrown',
  215: 'Mulgore',
  267: 'Hillsbrad Foothills',
  331: 'Ashenvale',
  357: 'Feralas',
  361: 'Felwood',
  394: 'Grizzly Hills',
  400: 'Thousand Needles',
  405: 'Desolace',
  406: 'Stonetalon Mountains',
  440: 'Tanaris',
  490: "Un'Goro Crater",
  491: 'Razorfen Kraul',
  493: 'Moonglade',
  495: 'Howling Fjord',
  618: 'Winterspring',
  1377: 'Silithus',
  1497: 'Undercity',
  1519: 'Stormwind City',
  1537: 'Ironforge',
  1637: 'Orgrimmar',
  1638: 'Thunder Bluff',
  1657: 'Darnassus',
  2100: 'Maraudon',
  2159: "Onyxia's Lair",
  2817: 'Crystalsong Forest',
  3277: 'Warsong Gulch',
  3358: 'Arathi Basin',
  3430: 'Eversong Woods',
  3433: 'Ghostlands',
  3483: 'Hellfire Peninsula',
  3487: 'Silvermoon City',
  3518: 'Nagrand',
  3519: 'Terokkar Forest',
  3520: 'Shadowmoon Valley',
  3521: 'Zangarmarsh',
  3522: "Blade's Edge Mountains",
  3523: 'Netherstorm',
  3524: 'Azuremyst Isle',
  3525: 'Bloodmyst Isle',
  3537: 'Borean Tundra',
  3540: 'Twisting Nether',
  3557: 'The Exodar',
  3703: 'Shattrath City',
  3711: 'Sholazar Basin',
  3805: "Zul'Aman",
  3820: 'Eye of the Storm',
  3836: "Magtheridon's Lair",
  3840: 'Tempest Keep',
  4080: "Isle of Quel'Danas",
  4197: 'Wintergrasp',
  4264: 'Halls of Stone',
  4265: 'The Nexus',
  4272: 'Halls of Lightning',
  4273: 'Ulduar',
  4277: 'Azjol-Nerub',
  4298: 'Acherus: The Ebon Hold',
  4384: 'Strand of the Ancients',
  4395: 'Dalaran',
  4415: 'The Violet Hold',
  4416: 'Gundrak',
  4493: 'Obsidian Sanctum',
  4494: "Ahn'kahet",
  4500: 'Eye of Eternity',
  4603: 'Vault of Archavon',
  4710: 'Isle of Conquest',
  4722: 'Trial of the Crusader',
  4723: 'Trial of the Champion',
  4809: 'Forge of Souls',
  4812: 'Icecrown Citadel',
  4813: 'Pit of Saron',
  4820: 'Halls of Reflection',
  4987: 'The Ruby Sanctum',
};

export const RACE_NAMES: Record<number, string> = {
  1: 'Human',
  2: 'Orc',
  3: 'Dwarf',
  4: 'Night Elf',
  5: 'Undead',
  6: 'Tauren',
  7: 'Gnome',
  8: 'Troll',
  10: 'Blood Elf',
  11: 'Draenei',
};

export const CLASS_NAMES: Record<number, string> = {
  1: 'Warrior',
  2: 'Paladin',
  3: 'Hunter',
  4: 'Rogue',
  5: 'Priest',
  6: 'Death Knight',
  7: 'Shaman',
  8: 'Mage',
  9: 'Warlock',
  11: 'Druid',
};

export const CLASS_COLORS: Record<number, string> = {
  1: '#C79C6E',
  2: '#F58CBA',
  3: '#ABD473',
  4: '#FFF569',
  5: '#FFFFFF',
  6: '#C41F3B',
  7: '#0070DE',
  8: '#69CCF0',
  9: '#9482C9',
  11: '#FF7D0A',
};

export const RACE_ICONS: Record<number, string> = {
  1: '🧑',
  2: '🧟',
  3: '⚒️',
  4: '🌿',
  5: '💀',
  6: '🐂',
  7: '⚙️',
  8: '🏹',
  10: '✨',
  11: '🔮',
};

export function getMapName(id: number): string {
  return MAP_NAMES[id] || `Map ${id}`;
}

export function getZoneName(id: number): string {
  return ZONE_NAMES[id] || `Zone ${id}`;
}
